export const UnitsList = [
  { id: "grams", value: "grams" },
  { id: "kilograms", value: "kilograms" },
  { id: "cups", value: "cups" },
  { id: "quarts", value: "quarts" },
  { id: "pints", value: "pints" },
  { id: "tbsp", value: "tbsp" },
  { id: "tsp", value: "tsp" },
  { id: "fl. oz", value: "fl. oz" },
  { id: "gallons", value: "gallons" },
  { id: "lbs", value: "lbs" },
  { id: "ml", value: "ml" },
  { id: "liters", value: "liters" },
  { id: "tt", value: "tt" },
  { id: "a/n", value: "a/n" },
  { id: "ea", value: "ea" },
  { id: "pinch", value: "pinch" },
];
